/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cocina_uno.gltf 
Author: Nicole Aragón (https://sketchfab.com/Nicole_Aragon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cocina-4c4e1b5e6508468b9650b7120c47d822
Title: Cocina
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cocina_uno.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.007']} position={[-0.006, -1.897, 0.085]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} position={[-0.748, 1.336, -0.55]} scale={[0.03, 0.001, 0.03]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.006']} position={[-0.774, 1.323, -0.63]} scale={[1.211, 0.945, 1.211]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} position={[-0.748, 1.401, -0.55]} scale={[1.377, 1.569, 1.377]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} position={[0.747, 1.336, -0.55]} scale={[0.03, 0.001, 0.03]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material_0} position={[0.747, 1.386, -0.55]} scale={[1, 1.459, 1]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.005']} position={[-0.766, 1.321, -1.756]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.material_0} position={[-0.748, 1.386, -1.752]} scale={[1, 1.459, 1]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.material_0} position={[0.747, 1.336, -1.752]} scale={[0.03, 0.001, 0.03]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.material_0} position={[0.747, 1.386, -1.752]} scale={[1, 1.459, 1]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.008']} position={[-0.006, -0.568, -1.191]} scale={[1.471, 1.706, 1.184]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Material.012']} position={[-0.006, -0.568, -1.191]} scale={[1.471, 1.706, 1.184]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['Material.002']} position={[-0.987, 0.761, 0.163]} rotation={[-Math.PI / 2, 0, 0]} scale={0.133} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['Material.001']} position={[-0.987, 0.761, 0.163]} rotation={[-Math.PI / 2, 0, 0]} scale={0.133} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Material.002']} position={[-0.647, 0.761, 0.163]} rotation={[-Math.PI / 2, 0, 0]} scale={0.133} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['Material.001']} position={[-0.647, 0.761, 0.163]} rotation={[-Math.PI / 2, 0, 0]} scale={0.133} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['Material.002']} position={[0.006, 0.719, 0.163]} rotation={[-Math.PI / 2, 0, 0]} scale={0.159} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['Material.001']} position={[0.006, 0.719, 0.163]} rotation={[-Math.PI / 2, 0, 0]} scale={0.159} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['Material.002']} position={[0.655, 0.761, 0.163]} rotation={[-Math.PI / 2, 0, 0]} scale={0.133} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['Material.001']} position={[0.655, 0.761, 0.163]} rotation={[-Math.PI / 2, 0, 0]} scale={0.133} />
      <mesh geometry={nodes.Object_44.geometry} material={materials['Material.002']} position={[0.993, 0.761, 0.163]} rotation={[-Math.PI / 2, 0, 0]} scale={0.133} />
      <mesh geometry={nodes.Object_46.geometry} material={materials['Material.001']} position={[0.993, 0.761, 0.163]} rotation={[-Math.PI / 2, 0, 0]} scale={0.133} />
      <mesh geometry={nodes.Object_48.geometry} material={materials['Material.004']} position={[-0.773, 1.257, -1.503]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials['Material.003']} position={[-0.006, -0.631, -1.191]} scale={[1.471, 1.706, 1.184]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials['Material.010']} position={[0.027, -1.05, -2.138]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials['Material.011']} position={[-0.84, 0.198, 0.167]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.123, 0.123, 0.059]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials['Material.011']} position={[-0.84, 0.212, 0.167]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.123, 0.123, 0.059]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials['Material.011']} position={[-0.84, -0.249, 0.167]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.09, 0.123, 0.059]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials['Material.011']} position={[-0.84, -0.346, 0.167]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.09, 0.123, 0.059]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials['Material.011']} position={[-0.84, -2.098, 0.167]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.09, 0.123, 0.059]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials['Material.011']} position={[-0.84, -2.223, 0.167]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.09, 0.123, 0.059]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials['Material.011']} position={[-0.84, -2.982, 0.167]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.09, 0.123, 0.059]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials['Material.009']} position={[0.027, -1.459, -2.375]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['Material.009']} position={[0.027, -0.822, -2.375]} />
    </group>
  )
}

useGLTF.preload('/cocina_uno.gltf')
