/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cocina_tres.gltf 
Author: media_mas (https://sketchfab.com/media_mas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cocina-lowpoly-92c07eb07c134106af3e0c2bfcb4fc7e
Title: Cocina - Lowpoly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cocina_tres.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-30.428, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 1.287, 1.499]}>
          <mesh geometry={nodes['cocina_02_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          <mesh geometry={nodes['cocina_02_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
          <mesh geometry={nodes['cocina_02_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
          <mesh geometry={nodes['cocina_02_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
          <mesh geometry={nodes['cocina_02_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
          <mesh geometry={nodes['cocina_02_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
          <mesh geometry={nodes['cocina_02_04_-_Default_0'].geometry} material={materials['04_-_Default']} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 1.287, 1.499]}>
          <mesh geometry={nodes['cocina_01_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          <mesh geometry={nodes['cocina_01_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
          <mesh geometry={nodes['cocina_01_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
          <mesh geometry={nodes['cocina_01_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
          <mesh geometry={nodes['cocina_01_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
          <mesh geometry={nodes['cocina_01_04_-_Default_0'].geometry} material={materials['04_-_Default']} />
          <mesh geometry={nodes['cocina_01_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cocina_tres.gltf')
