/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cocina_dos.gltf 
Author: DidierA (https://sketchfab.com/DidierA)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/electric-stove-estufa-electrica-b64ec42b3f784ea6ab58d862328fd0cc
Title: Electric Stove - Estufa Electrica
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cocina_dos.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Mesh1_Metal_0.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Mesh2_Resistencia_0.geometry} material={materials.Resistencia} />
        <mesh geometry={nodes.Mesh3_Resistencia_0.geometry} material={materials.Resistencia} />
        <mesh geometry={nodes.Mesh4_Resistencia_0.geometry} material={materials.Resistencia} />
        <mesh geometry={nodes.Mesh5_Resistencia_0.geometry} material={materials.Resistencia} />
        <mesh geometry={nodes.Mesh6_vidrio_0.geometry} material={materials.vidrio} />
        <mesh geometry={nodes.Mesh7_parrilla__0.geometry} material={materials.parrilla} />
        <mesh geometry={nodes.Mesh8_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh8_plastico_0.geometry} material={materials.plastico} />
        <mesh geometry={nodes.Mesh9_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh9_plastico_0.geometry} material={materials.plastico} />
        <mesh geometry={nodes.Mesh10_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh10_plastico_0.geometry} material={materials.plastico} />
        <mesh geometry={nodes.Mesh11_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh11_plastico_0.geometry} material={materials.plastico} />
        <mesh geometry={nodes.Mesh12_Color_M09_0.geometry} material={materials.Color_M09} />
        <mesh geometry={nodes.Mesh13_parrilla__0.geometry} material={materials.parrilla} />
        <mesh geometry={nodes.Mesh14_parrilla__0.geometry} material={materials.parrilla} />
      </group>
    </group>
  )
}

useGLTF.preload('/cocina_dos.gltf')
